# Generated by Django 3.0.7 on 2020-07-04 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sg1_gps_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='myData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_mode', models.BooleanField()),
                ('nmod_nav_ok', models.BooleanField()),
                ('nmod_gps_ok', models.BooleanField()),
                ('set_polaris_ok', models.BooleanField()),
                ('gps_latitude', models.FloatField(default=0)),
                ('gps_longitude', models.FloatField(default=0)),
                ('gps_altitude', models.FloatField(default=0)),
                ('gps_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='stargate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mydata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.myData')),
            ],
        ),
    ]
