# Generated by Django 3.0.7 on 2020-07-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20200704_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LMST', models.FloatField(default=0)),
                ('ra_sv', models.FloatField(default=0)),
                ('ra_sp', models.FloatField(default=0)),
                ('ra_av', models.FloatField(default=0)),
                ('ra_sp_steps', models.FloatField(default=0)),
                ('ra_dir', models.CharField(default='None', max_length=10)),
                ('dec_sv', models.FloatField(default=0)),
                ('dec_sp', models.FloatField(default=0)),
                ('dec_av', models.FloatField(default=0)),
                ('dec_sp_steps', models.FloatField(default=0)),
                ('dec_dir', models.CharField(default='None', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='myStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observe', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='myTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star1', models.CharField(default='Star1', max_length=25)),
                ('star2', models.CharField(default='Star2', max_length=25)),
                ('star3', models.CharField(default='Star3', max_length=25)),
                ('star1_ok', models.CharField(default='incomplete', max_length=25)),
                ('star2_ok', models.CharField(default='incomplete', max_length=25)),
                ('star3_ok', models.CharField(default='incomplete', max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='SG1',
        ),
        migrations.AddField(
            model_name='stargate',
            name='mycalc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sensors.myCalc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stargate',
            name='mystatus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sensors.myStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stargate',
            name='mytarget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sensors.myTarget'),
            preserve_default=False,
        ),
    ]
