# Generated by Django 3.0.7 on 2020-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20200704_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stargate',
            name='id',
        ),
        migrations.AlterField(
            model_name='stargate',
            name='name',
            field=models.CharField(default='SG1', max_length=10, primary_key=True, serialize=False),
        ),
    ]
